---
title: "Practical 2"
author: "Colin Steffe, Virany Kho, Jasmine Mawjee, Adela Sahraoui"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---


```{r}
library(here)
library(quantmod)  
library(dplyr)
library(tidyverse)
library(ggplot2)
library(plotly)
library(tidyquant)

# Read in the data
load(file = here::here("stocks.Rdata"))
```


```{r}

  #rect()
fig.rect <- stocks %>% plot_ly( x = ~stocks$ref.date, type = "candlestick",
                    open = ~stocks$price.open, close = ~stocks$price.close,
                    high = ~stocks$price.high, low = ~stocks$price.low) %>% 
  layout(title = "Stock Prices Candlestick Chart rect()")
fig.rect

  #segments()

fig.seg <- plot_ly(stocks, x = ~stocks$ref.date, xend = ~stocks$ref.date, color = ~stocks$price.close > stocks$price.open,
             colors = c("red", "forestgreen"), hoverinfo = "none") 
fig.seg <- fig.seg %>% add_segments(y = ~stocks$price.low, yend = ~stocks$price.high, size = I(1)) 
fig.seg <- fig.seg %>% add_segments(y = ~stocks$price.open, yend = ~stocks$price.close, size = I(3)) 
fig.seg <- fig.seg %>% layout(title = "Stock Prices Candlestick Chart segments()", showlegend =FALSE, yaxis = list(title = "Price")) 
fig.seg <- fig.seg %>% rangeslider()

fig.seg
```

```{r}
# candle plot of the 4 stocks

dif.stocks <- unique(stocks$ticker)

for (i in 1:length(dif.stocks)){

candplot<- stocks %>% filter (ticker == dif.stocks[i]) %>% ggplot(aes(x = ref.date, y = price.close)) +
    geom_barchart(aes(open = price.open, high = price.high, low = price.low, close = price.close),colour_up = "green", colour_down = "red") +
    labs(title = paste(dif.stocks[i], "Candle Chart"), y = "Closing Price", x = "") + 
    theme_tq()

print(candplot)
}

```

b) 

```{r}

forth_log <- stocks %>% filter(ticker == "NVDA")

log_returns <- data.frame(matrix(NA, nrow = nrow(forth_log), ncol = 1))
colnames(log_returns) <- "neg_log_returns"

for (i in 1:nrow(forth_log)){
  return_i <- - log(forth_log$price.close[i+1]/forth_log$price.close[i])
  
  log_returns$neg_log_returns[i] <- return_i
}

log_returns <- cbind(forth_log,log_returns)

log_returns %>% ggplot(aes(x = ref.date, y = neg_log_returns ))+geom_line()

```

