---
title: "Practical 3: Web Traffic"
author: "Colin Steffe, Virany Kho, Jasmine Mawjee, Adela Sahraoui"
date: "11/25/2021"
output: html_document
---

```{r data preparation, echo=F, message=F, warning=F}

library(here)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(plotly)
library(fpp3)

# Read in the data
load(file = here::here("traffic.Rdata"))

# Convert into tibble 
pageviews <- as_tibble(pageviews)

# Create new column
type <- c("Elizabeth_II", 
          "United_States",
          "Queen_Victoria",
          "World_War_II",
          "World_War_I",
          "George_VI",
          "United_Kingdom",
          "Princess_Margaret,_Countess_of_Snowdon",
          "Prince_Philip,_Duke_of_Edinburgh",
          "Winston_Churchill",
          "Diana,_Princess_of_Wales",
          "2016_Summer_Olympics")

# Add new column
pageviews <- cbind(pageviews,
                   type)

# Reorder colum
pageviews <- pageviews[, c(804, 1:803)]

# Pivot data frame 
pageviews <- pageviews %>% 
             pivot_longer(!type, 
                          names_to = "date", 
                          values_to = "dailycount")

# Convert column date into date format
pageviews$date <- as.Date(pageviews$date, format = "%Y-%m-%d")

# Convert into tsibble
pageviews_ts <- tsibble(pageviews, 
                        index = date,
                        key = c(type, dailycount)) # since duplicates need to keys

# str(pageviews_ts) # to verify the structure of dataframe

```

# Informative Plots

- time series plot
- rolling window
- seasonal plot
- time series decompostion
- ACF plot


```{r plots, echo=F, message=F, warning=F}


            
```