---
title: "Practical 1: High Water Levels"
author: "Colin Steffe, Virany Kho, Jasmine Mawjee, Adela Sahraoui"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}

# Read in the data
load(file = here::here("niveau.Rdata"))

```

```{r}

library(lubridate)
library(tibble)
library(tsibble)
library(fpp3)

# Convert column 8 into date type
niveau <- niveau %>%
          mutate(Zeitpunkt_des_Auftretens = as_datetime(Zeitpunkt_des_Auftretens))
#niveau$Zeitpunkt_des_Auftretens[1]

# Transform into tibble
niveau.ts <- niveau %>%
             as_tsibble(index = Zeitpunkt_des_Auftretens,
                        key = Zeitstempel)

```

```{r}

# Plot the time series
niveau.ts %>% 
  ggplot() + 
  geom_line(mapping = aes(x = Zeitpunkt_des_Auftretens, 
                          y = Wert)) +
  labs(title = "Time Series: Water Levels",
       x = "Time of Occurrence",
       y = "Value") + 
  geom_hline(yintercept=328.4, linetype="dashed", color = "red")

```
## Value Distribution

We observe a right-skwed distribution of the water level values.

```{r}

# Histogram
niveau.ts %>% 
  ggplot() + 
  geom_histogram(mapping = aes(Wert),
                 stat = "count") +
  geom_density(mapping = aes(Wert), stat = "density", colour="red") +
  labs(title = "Water Levels Frequencies",
       x = "Value",
       y = "Frequency")

```

